USE [Pcfastory]
GO
/****** Object:  Table [dbo].[TAB_CATEGORIA]    Script Date: 25-05-2017 15:06:20 ******/
SET ANSI_NULLS ON
GO
SET QUOTED_IDENTIFIER ON
GO
CREATE TABLE [dbo].[TAB_CATEGORIA](
	[ID_CAT] [int] NOT NULL,
	[NOM_CAT] [nvarchar](50) NULL,
 CONSTRAINT [PK_TAB_CATEGORIA] PRIMARY KEY CLUSTERED 
(
	[ID_CAT] ASC
)WITH (PAD_INDEX = OFF, STATISTICS_NORECOMPUTE = OFF, IGNORE_DUP_KEY = OFF, ALLOW_ROW_LOCKS = ON, ALLOW_PAGE_LOCKS = ON) ON [PRIMARY]
) ON [PRIMARY]

GO
/****** Object:  Table [dbo].[TBL_DETALLE]    Script Date: 25-05-2017 15:06:20 ******/
SET ANSI_NULLS ON
GO
SET QUOTED_IDENTIFIER ON
GO
CREATE TABLE [dbo].[TAB_DETALLE](
	[ID_VENTA] [int] NULL,
	[ID_USUARIO] [int] NULL,
	[ID_PRODUCTO] [int] NULL
) ON [PRIMARY]

GO
/****** Object:  Table [dbo].[TBL_PRODUCTO]    Script Date: 25-05-2017 15:06:20 ******/
SET ANSI_NULLS ON
GO
SET QUOTED_IDENTIFIER ON
GO
SET ANSI_PADDING ON
GO
CREATE TABLE [dbo].[TAB_PRODUCTO](
	[ID_PRO] [int] IDENTITY(1,1) NOT NULL,
	[NOM_PRO] [varchar](50) NULL,
	[DESCRIPCION_PRO] [varchar](50) NULL,
	[PRECIO_PRO] [int] NULL,
	[STOCK_PRO] [int] NULL,
	[FOTO_PRO] [varchar](50) NULL,
	[ID_CAT] [int] NULL,
 CONSTRAINT [PK_TAB_PRODUCTO] PRIMARY KEY CLUSTERED 
(
	[ID_PRO] ASC
)WITH (PAD_INDEX = OFF, STATISTICS_NORECOMPUTE = OFF, IGNORE_DUP_KEY = OFF, ALLOW_ROW_LOCKS = ON, ALLOW_PAGE_LOCKS = ON) ON [PRIMARY]
) ON [PRIMARY]

GO
SET ANSI_PADDING OFF
GO
/****** Object:  Table [dbo].[TBL_USUARIOS]    Script Date: 25-05-2017 15:06:20 ******/
SET ANSI_NULLS ON
GO
SET QUOTED_IDENTIFIER ON
GO
SET ANSI_PADDING ON
GO
CREATE TABLE [dbo].[TAB_USUARIOS](
	[ID_USUARIO] [int] IDENTITY(1,1) NOT NULL,
	[RUT] [int] NULL,
	[NOMBRE_USER] [varchar](50) NULL,
	[EMAIL_USER] [varchar](50) NULL,
	[USERNAME] [varchar](50) NULL,
	[PASSWORD] [varchar](50) NULL,
	[TIPO_USER] [bit] NULL,
 CONSTRAINT [PK_TAB_USUARIOS] PRIMARY KEY CLUSTERED 
(
	[ID_USUARIO] ASC
)WITH (PAD_INDEX = OFF, STATISTICS_NORECOMPUTE = OFF, IGNORE_DUP_KEY = OFF, ALLOW_ROW_LOCKS = ON, ALLOW_PAGE_LOCKS = ON) ON [PRIMARY]
) ON [PRIMARY]

GO
SET ANSI_PADDING OFF
GO
/****** Object:  Table [dbo].[TBL_VENTA]    Script Date: 25-05-2017 15:06:20 ******/
SET ANSI_NULLS ON
GO
SET QUOTED_IDENTIFIER ON
GO
CREATE TABLE [dbo].[TAB_VENTA](
	[ID_VENT] [int] IDENTITY(1,1) NOT NULL,
	[FECHA_VENT] [date] NULL,
	[TOTAL_VENT] [int] NULL,
 CONSTRAINT [PK_TAB_VENTA] PRIMARY KEY CLUSTERED 
(
	[ID_VENT] ASC
)WITH (PAD_INDEX = OFF, STATISTICS_NORECOMPUTE = OFF, IGNORE_DUP_KEY = OFF, ALLOW_ROW_LOCKS = ON, ALLOW_PAGE_LOCKS = ON) ON [PRIMARY]
) ON [PRIMARY]

GO
ALTER TABLE [dbo].[TAB_DETALLE]  WITH CHECK ADD FOREIGN KEY([ID_PRODUCTO])
REFERENCES [dbo].[TAB_PRODUCTO] ([ID_PRO])
GO
ALTER TABLE [dbo].[TAB_DETALLE]  WITH CHECK ADD FOREIGN KEY([ID_USUARIO])
REFERENCES [dbo].[TAB_USUARIOS] ([ID_USUARIO])
GO
ALTER TABLE [dbo].[TAB_DETALLE]  WITH CHECK ADD FOREIGN KEY([ID_VENTA])
REFERENCES [dbo].[TAB_VENTA] ([ID_VENT])
GO
ALTER TABLE [dbo].[TAB_PRODUCTO]  WITH CHECK ADD FOREIGN KEY([ID_CAT])
REFERENCES [dbo].[TAB_CATEGORIA] ([ID_CAT])
GO
